#### COMPARE OBSERVED  AND EXPECTED MutSpecs 

rm(list=ls(all=TRUE))

pdf("../../Body/4Figures/MutSpecObservedVsExpected.R.pdf", width = 14)

ColVec=c('gray',rgb(0,1,0,0.2),'gray','gray','gray',rgb(1,0,0,0.2),rgb(1,0,0,1),'gray','gray','gray',rgb(0,1,0,1),'gray'); length(ColVec)

# Observed (Nd6 gene is deleted) Syn MutSpecs (generated by GlobalHumanTree.MutSpecsObserved192&12.R)
ObsSyn192 = read.table("../../Body/2Derived/MutSpec192SynObsNoNd6LightChain.txt")
names(ObsSyn192)[3] = c('NumbObs')
ObsSyn12  = read.table("../../Body/2Derived/MutSpec12SynObsNoNd6LightChain.txt")
names(ObsSyn12)[2] = c('NumbObs')

# expected (Nd6 gene is deleted) Syn and All MutSpec (generated by 07.MutationGeneratorForSnpEff.ExpectedMutSpeks.R)
ExpSyn12 = read.table("../../Body/1Raw/FromCovidProject/HumanMtDnaRefSeq.fasta.ExtensiveMut.vcf.ann.ExpectedMutSpec12.txt"); ExpSyn12 = ExpSyn12[ExpSyn12$Subset == 'Syn',]
names(ExpSyn12)[c(1,2)]=c('Subst','NumbExp')
ExpSyn192 = read.table("../../Body/1Raw/FromCovidProject/HumanMtDnaRefSeq.fasta.ExtensiveMut.vcf.ann.ExpectedMutSpec192.txt"); ExpSyn192 = ExpSyn192[ExpSyn192$Subset == 'Syn',]
names(ExpSyn192)[c(3)]=c('NumbExp')

#### MutSpec12
MutSpec12 = merge(ObsSyn12,ExpSyn12, by = c('Subst')); 
MutSpec12=MutSpec12[order(MutSpec12$Subst),]
MutSpec12$FreqObs = MutSpec12$NumbObs/sum(MutSpec12$NumbObs); 
MutSpec12$FreqExp = MutSpec12$NumbExp/sum(MutSpec12$NumbExp); 
MutSpec12$ObsToExpFreq = MutSpec12$FreqObs/MutSpec12$FreqExp

barplot(MutSpec12$ObsToExpFreq, names = MutSpec12$Subst, col = ColVec, main = paste("Exp/Obs Syn substitutions mtDNA (no ND6)")) # dev.off()

#### MutSpec192
MutSpec192 = merge(ObsSyn192,ExpSyn192, by = c('Subst','Context','names')); 
MutSpec192=MutSpec192[order(MutSpec192$Subst),]
MutSpec192$FreqObs = MutSpec192$NumbObs/sum(MutSpec192$NumbObs); 
MutSpec192$FreqExp = MutSpec192$NumbExp/sum(MutSpec192$NumbExp); 
MutSpec192$ObsToExpFreq = MutSpec192$FreqObs/MutSpec192$FreqExp

ColVec=c(rep('gray',16),rep(rgb(0,1,0,0.2),16),rep('gray',16),rep('gray',16),rep('gray',16),rep(rgb(1,0,0,0.2),16),rep(rgb(1,0,0,1),16),rep('gray',16),rep('gray',16),rep('gray',16),rep(rgb(0,1,0,1),16),rep('gray',16)); length(ColVec)
barplot(MutSpec192$ObsToExpFreq, names = MutSpec192$Subst, cex.names = 0.5, col = ColVec, main = paste("Exp/Obs Syn substitutions mtDNA (no ND6)")) # dev.off()

dev.off()

write.table(MutSpec192,"../../Body/3Results/MutSpec192ObsToExpSynNoNd6.txt", row.names = FALSE, quote = FALSE, sep = '\t')
write.table(MutSpec12,"../../Body/3Results/MutSpec12ObsToExpSynNoNd6.txt", row.names = FALSE, quote = FALSE, sep = '\t')

